routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::middleware('backend')
  ->namespace('Backend')
  ->prefix('manager')
  ->as('backend.')
  ->group(function() {
    Route::get('/', 'DashboardController@index')
      ->name('dashboard');

    Route::post('categories/move', 'CategoriesController@move')
          ->name('categories.move');
    Route::resource('/categories', 'CategoriesController');

    Route::get('/videos/request', 'VideosController@request')
        ->name('videos.request');
    Route::post('/videos/import', 'VideosController@import')
        ->name('videos.import');
    Route::resource('/videos', 'VideosController');

      Route::get('/authors/request', 'AuthorsController@request')
          ->name('authors.request');
      Route::post('/authors/import', 'AuthorsController@import')
          ->name('authors.import');
    Route::resource('/authors', 'AuthorsController');

    Route::resource('/news', 'NewsController');

    Route::resource('/articles', 'ArticlesController');

    Route::resource('/pages', 'PagesController');

    Route::resource('/comments', 'CommentsController');

    Route::resource('/settings', 'SettingsController');

    Route::resource('/permissions', 'PermissionsController');

    Route::resource('/roles', 'RolesController');

    Route::resource('/managers', 'ManagersController');
  });

Auth::routes();

Route::middleware('frontend')
    ->namespace('Frontend')
    ->group(function() {
        Route::get('/', 'IndexController@index');

        Route::get('/articles/{url}', 'ArticlesController@show');

        Route::get('/categories/{url}', 'CategoriesController@show');

        Route::get('/authors/{url}', 'AuthorsController@show');

        Route::get('/{url}', 'VideosController@show');

    });

app/Author.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Author extends Model
{
    public function videos()
    {
        return $this->hasMany('App\Video');
    }

    public function scopeByUrl($query, $url)
    {
        $query->where('url', $url);
    }

    public function scopeByChannelId($query, $channelId)
    {
        $query->where('channel_id', $channelId);
    }
}

app/Http/Controllers/Backend/ArticlesController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Article;
use View;

class ArticlesController extends Controller
{

  public function __construct()
  {
    View::share(['menuItem' => 'articles']);
  }
  /**
   * Display a listing of the resource.
   *
   * @return \Illuminate\Http\Response
   */
  public function index()
  {
    $crumbs = [
      'Статьи' => '',
    ];

    $articles = Article::paginate(10);

    return view('backend.articles.index', compact('crumbs', 'articles'));
  }

  /**
   * Show the form for creating a new resource.
   *
   * @return \Illuminate\Http\Response
   */
  public function create()
  {
    $crumbs = [
      'Статьи' => route('backend.articles.index'),
      'Создать' => '',
    ];

    return view('backend.articles.create', compact('crumbs'));
  }

  /**
   * Store a newly created resource in storage.
   *
   * @param  \Illuminate\Http\Request  $request
   * @return \Illuminate\Http\Response
   */
  public function store(Request $request)
  {
      //
  }

  /**
   * Display the specified resource.
   *
   * @param  int  $id
   * @return \Illuminate\Http\Response
   */
  public function show($id)
  {
      //
  }

  /**
   * Show the form for editing the specified resource.
   *
   * @param  int  $id
   * @return \Illuminate\Http\Response
   */
  public function edit($id)
  {
      //
  }

  /**
   * Update the specified resource in storage.
   *
   * @param  \Illuminate\Http\Request  $request
   * @param  int  $id
   * @return \Illuminate\Http\Response
   */
  public function update(Request $request, $id)
  {
      //
  }

  /**
   * Remove the specified resource from storage.
   *
   * @param  int  $id
   * @return \Illuminate\Http\Response
   */
  public function destroy($id)
  {
      //
  }
}

app/Http/Controllers/Backend/AuthorsController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Author;
use View;
use Youtube;

class AuthorsController extends Controller
{
    public function __construct()
    {
        View::share(['menuItem' => 'authors']);
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $crumbs = [
            'Авторы' => '',
        ];

        $authors = Author::paginate(10);

        return view('backend.authors.index', compact('crumbs', 'authors'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $crumbs = [
            'Авторы' => route('backend.authors.index'),
            'Создать' => '',
        ];

        return view('backend.authors.create', compact('crumbs'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required|unique:authors|max:255',
            'channel_id' => 'required|unique:authors|max:255',
            'url' => 'required|unique:authors|max:255'
        ]);

        $author = new Author;
        $author->name = $request->input('name');
        $author->channel_id = $request->input('channel_id');
        $author->url = $request->input('url');
        $author->save();

        $request->session()->flash('message', "Автор <strong>$author->name</strong> добавлен.");
        if ($request->has('more')) {
            return redirect()->route('backend.authors.create');
        }
        return redirect()->route('backend.authors.index');
    }

    public function request()
    {
        $crumbs = [
            'Авторы' => route('backend.authors.index'),
            'Импорт' => '',
        ];

        return view('backend.authors.request', compact('crumbs'));
    }

    public function import(Request $request)
    {
        $request->validate([
            'channel_id' => 'required',
        ]);

        Youtube::setApiKey('AIzaSyA2aKJiEsSfAi3cblRmw-co7TJ95zTlQ_A');
        $rawChannel = Youtube::getChannelById($request->input('channel_id'));
        $author = new Author;
        $author->name = $rawChannel->snippet->title;
        $author->url = translit($rawChannel->snippet->title);
        $author->channel_id = $rawChannel->id;
        $author->channel_title = $rawChannel->snippet->title;
        $author->save();

        $request->session()->flash('message', "Автор <strong>$author->name</strong> добавлен.");
        if ($request->has('more')) {
            return redirect()->route('backend.authors.create');
        }
        return redirect()->route('backend.authors.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $crumbs = [
            'Авторы' => route('backend.authors.index'),
            'Редактировать' => '',
        ];

        $author = Author::findOrFail($id);

        return view('backend.authors.edit', compact('author', 'crumbs'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'name' => 'required|unique:authors,id,' . $id . '|max:255',
            'channel_id' => 'required|unique:authors,id,' . $id . '|max:255',
            'url' => 'required|unique:authors,id,' . $id . '|max:255'
        ]);

        $author = Author::findOrFail($id);
        $author->name = $request->input('name');
        $author->channel_id = $request->input('channel_id');
        $author->url = $request->input('url');
        $author->save();

        $request->session()->flash('message', "Автор <strong>$author->name</strong> обновлен.");
        return redirect()->route('backend.authors.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Author::destroy($id);
        return ['result' => 'success'];
    }
}

app/Http/Controllers/Backend/CategoriesController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Category;
use View;

class CategoriesController extends Controller
{
  public function __construct()
  {
    View::share(['menuItem' => 'categories']);
  }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
      $crumbs = [
        'Категории' => '',
      ];

        $categories = Category::getTree();

      $count = Category::count();

      return view('backend.categories.index', compact('crumbs', 'categories', 'count'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
      $crumbs = [
        'Категории' => route('backend.categories.index'),
        'Создать' => '',
      ];

        $categories = Category::getTree();

      return view('backend.categories.create', compact('crumbs', 'categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required|max:255',
            'url' => 'required|unique:categories|max:255',
        ]);

        $category = new Category;
        $category->name = $request->input('name');
        $category->url = $request->input('url');
        $parent = Category::where('url', $request->input('parent_id'))
            ->first();
        $category->parent_id = $parent ? $parent->id : 0;
        $category->summary = $request->input('summary');
        $category->content = $request->input('content');
        $category->save();

        $request->session()->flash('message', "Категория <strong>$category->name</strong> добавлена.");
        if ($request->has('more')) {
            return redirect()->route('backend.categories.create');
        }
        return redirect()->route('backend.categories.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $crumbs = [
            'Категории' => route('backend.categories.index'),
            'Редактировать' => '',
        ];

        $category = Category::findOrFail($id);

        $categories = Category::getTree();

        return view('backend.categories.edit', compact('crumbs', 'category', 'categories'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'name' => 'required|max:255',
            'url' => 'required|unique:categories,id,'.$id.'|max:255',
        ]);

        $category = Category::findOrFail($id);
        $category->name = $request->input('name');
        $category->url = $request->input('url');
        $parent = Category::where('url', $request->input('parent_id'))
            ->first();
        $category->parent_id = $parent ? $parent->id : 0;
        $category->summary = $request->input('summary');
        $category->content = $request->input('content');
        $category->save();

        $request->session()->flash('message', "Категория <strong>$category->name</strong> обновлена.");
        return redirect()->route('backend.categories.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Category::destroyWithChildren($id);
    }

    public function move(Request $request)
    {
        if (!$request->ajax()) {
            abort('405');
        }

        $request->validate([
            'id' => 'integer',
            'parent_id' => 'integer',
            'ids' => 'array',
        ]);

        $id = $request->input('id');
        $parentId = $request->input('parent_id');
        $ids = collect($request->input('ids'));

        // Get item
        $category = Category::findOrFail($id);
        $category->parent_id = $parentId;
        $category->save();

        // Get all siblings and sort them
        $siblings = Category::where('parent_id', $parentId)
            ->get()
            ->keyBy('id');
        $position = 0;
        foreach ($ids as $item) {
            $siblings[$item]->position = $position++;
            $siblings[$item]->save();
        }
    }
}

app/Http/Controllers/Backend/CommentsController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Comment;
use View;

class CommentsController extends Controller
{

  public function __construct()
  {
    View::share(['menuItem' => 'comment']);
  }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
      $crumbs = [
        'Комментарии' => '',
      ];

      $comments = Comment::paginate(10);

      return view('backend.comments.index', compact('crumbs', 'comments'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
      $crumbs = [
        'Комментарии' => route('backend.comments.index'),
        'Создать' => '',
      ];

      return view('backend.comments.create', compact('crumbs'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Backend/DashboardController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use View;

use DOMDocument;

class DashboardController extends Controller
{
  public function __construct()
  {
    View::share(['menuItem' => 'dashboard']);
  }

    public function index()
    {
      $crumbs = [
        'Панель управления' => '',
      ];

      return view('backend.dashboard.index', compact('crumbs'));
    }

}

app/Http/Controllers/Frontend/AuthorsController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\Author;
use App\Video;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class AuthorsController extends Controller
{
    public function show($url)
    {
        $author = Author::ByUrl($url)
            ->firstOrFail();

        $videos = Video::byAuthor($author->id)
            ->paginate(9);

        return view('frontend.authors.show', compact('author', 'videos'));
    }
}

resources/views/backend/authors/create.blade.php
@extends('backend.master')

@section('content')
  @include('backend.partials.h1', ['h1' => 'Новый автор'])

<div class="row">
  <div class="col-md-12">
    <div class="panel panel-default">
      <div class="panel-body">
        <form method="POST" action="{{ route('backend.authors.store') }}">
          {{ csrf_field() }}
          <div class="form-group">
            <label for="name">Название</label>
            <input type="text" class="form-control" data-transliterable="url"  name="name" id="name" value="{{ old('name') }}">
          </div>
          <div class="form-group">
            <label for="channel_id">Id канала</label>
            <input type="text" class="form-control" name="channel_id" id="channel_id" value="{{ old('channel_id') }}">
          </div>
          <div class="form-group">
            <label for="url">Url</label>
            <input type="text" class="form-control" name="url" id="url" value="{{ old('url') }}">
          </div>
          <button type="submit" name="save" value="1" class="btn btn-default">Создать</button>
          <button type="submit" name="more" value="1" class="btn btn-default">Создать и добавить еще</button>
        </form>
      </div>
    </div>
  </div>
</div>
@endsection

resources/views/backend/authors/edit.blade.php
@extends('backend.master')

@section('content')
  @include('backend.partials.h1', ['h1' => $author->name])

  <div class="row">
    <div class="col-md-12">
      <div class="panel panel-default">
        <div class="panel-body">
          <form method="POST" action="{{ route('backend.authors.update', $author->id) }}">
            {{ csrf_field() }}
            {{ method_field('PUT') }}
            <div class="form-group">
              <label for="name">Название</label>
              <input type="text" class="form-control" data-transliterable="url"  name="name" id="name" value="{{ $author->name }}">
            </div>
            <div class="form-group">
              <label for="channel_id">Id канала</label>
              <input type="text" class="form-control" name="channel_id" id="hannel_id" value="{{ $author->channel_id }}">
            </div>
            <div class="form-group">
              <label for="url">Url</label>
              <input type="text" class="form-control" name="url" id="url" value="{{ $author->url }}">
            </div>
            <button type="submit" name="save" value="1" class="btn btn-default">Обновить</button>
          </form>
        </div>
      </div>
    </div>
  </div>
@endsection

resources/views/backend/authors/index.blade.php
@extends('backend.master')

@section('content')
  @include('backend.partials.h1', ['h1' => $authors->total().' '.pluralize($authors->total(), 'автор,автора,авторов')])

<div class="row">
  <div class="col-md-12">
    <div class="panel panel-default">
      <div class="panel-heading">
        <a href="{{ route('backend.authors.create') }}" class="btn btn-md btn-primary">Создать автора</a>
        <a href="{{ route('backend.authors.request') }}" class="btn btn-md btn-primary">Импортировать автора</a>
      </div>
        <div class="panel-body">
          {{ $authors->links() }}
          <table class="table table-striped">
            <thead>
            <tr>
              <th>Название</th>
              <th>Url</th>
              <th>Id канала</th>
              <th class="operations">Операции</th>
            </tr>
            </thead>
            <tbody>
            @forelse ($authors as $author)
              <tr data-id="{{ $author->id }}">
                <td><a href="{{ route('backend.authors.edit', $author->id) }}">{{ $author->name }}</a></td>
                <td>{{ $author->url }}</td>
                <td>{{ $author->channel_id }}</td>
                <td class="operations"><a href="#" data-action="delete"><i class="fa fa-window-close" aria-hidden="true"></i></a></td>
              </tr>
            @empty
              <tr>
                <td colspan="3">Авторы не добавлены</td>
              </tr>
            @endforelse
            </tbody>
          </table>
          {{ $authors->links() }}
      </div>
    </div>
  </div>
</div>
@endsection

@push('scripts')
  <script>
    $(function() {
        $('[data-action=delete]').click(function() {
           var id = $(this).closest('[data-id]').data('id');
           $.post('{{ route('backend.authors.index') }}/' + id, { _method: 'DELETE' }, function(data) {
               window.location.reload(true);
           });
           return false;
        });
    });
  </script>
@endpush

resources/views/backend/authors/request.blade.php
@extends('backend.master')

@section('content')
  @include('backend.partials.h1', ['h1' => 'Импорт автора'])

<div class="row">
  <div class="col-md-12">
    <div class="panel panel-default">
      <div class="panel-body">
        <form method="POST" action="{{ route('backend.authors.import') }}">
          {{ csrf_field() }}
          <div class="form-group">
            <label for="channel_id">Id канала</label>
            <input type="text" class="form-control" name="channel_id" id="channel_id" value="{{ old('channel_id') }}">
          </div>
          <button type="submit" name="save" value="1" class="btn btn-default">Создать</button>
          <button type="submit" name="more" value="1" class="btn btn-default">Создать и добавить еще</button>
        </form>
      </div>
    </div>
  </div>
</div>
@endsection